var shelter = [
  {
    "Center_Name": "Mainchance",
    "Borough": "Manhattan",
    "Service": "Drop in",
    "Street_Address": "120 East 32nd Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": null,
    "URL": null,
    "Comments": "Open 24 hours"
  },
  {
    "Center_Name": "The Living Room",
    "Borough": "Bronx",
    "Service": "Drop in",
    "Street_Address": "1241 Lafayette Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": null,
    "URL": null,
    "Comments": "Open 24 hours"
  },
  {
    "Center_Name": "Olivieri Center",
    "Borough": "Manhattan",
    "Service": "Drop in",
    "Street_Address": "257 West 30th Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": null,
    "URL": null,
    "Comments": "Open from 7:30 a.m.-8:30 p.m. This program remain open 24 hours during winter months"
  },
  {
    "Center_Name": "The Gathering Place",
    "Borough": "Brooklyn",
    "Service": "Drop in",
    "Street_Address": "2402 Atlantic Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": null,
    "URL": null,
    "Comments": "Open from 7:30 a.m.-8:30 p.m. This program remain open 24 hours during winter months"
  },
  {
    "Center_Name": "Project Hospitality",
    "Borough": "Staten Island",
    "Service": "Drop in",
    "Street_Address": "25 Central Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": null,
    "URL": null,
    "Comments": "Open from 7:30 a.m.-8:30 p.m. This program remain open 24 hours during winter months"
  },
  {
    "Center_Name": "Safe Horizon, Inc",
    "Borough": "Manhattan",
    "Service": "Crises",
    "Street_Address": "214 West 30th Street",
    "Latitude": "40.74862808",
    "Longitude": "-73.99338311",
    "Phone": "(212) 268-3943",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Covenant House",
    "Borough": "Manhattan",
    "Service": "Crises",
    "Street_Address": "427 West 52nd Street,",
    "Latitude": "40.76543659",
    "Longitude": "-73.98926243",
    "Phone": "(212) 613-0300 ext. 0532",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Covenant House",
    "Borough": "Manhattan",
    "Service": "Crises",
    "Street_Address": "460 West 41st Street",
    "Latitude": "40.75854147",
    "Longitude": "-73.99557687",
    "Phone": "(212) 613-0300 ext. 0531",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Ali Forney Center",
    "Borough": "Brooklyn",
    "Service": "Crises",
    "Street_Address": "241 Taffee Place",
    "Latitude": "40.69090313",
    "Longitude": "-73.95931031",
    "Phone": "(212) 206-0574",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "The Turning Point Sunset Terrace",
    "Borough": "Brooklyn",
    "Service": "Crises",
    "Street_Address": "319-321 42nd Street",
    "Latitude": "40.65202799",
    "Longitude": "-74.00935105",
    "Phone": "(718) 640-1560 ext. 9025",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Ali Forney Center",
    "Borough": "Brooklyn",
    "Service": "Crises",
    "Street_Address": "216 23rd Street",
    "Latitude": "40.66053404",
    "Longitude": "-73.99542364",
    "Phone": "(212) 206-0574",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "The Turning Point",
    "Borough": "Brooklyn",
    "Service": "Crises",
    "Street_Address": "5220 Fourth Avenue",
    "Latitude": "40.64510298",
    "Longitude": "-74.01450042",
    "Phone": "(718) 439-0077",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Cardinal McCloskey",
    "Borough": "Bronx",
    "Service": "Drop in",
    "Street_Address": "333 East 149th Street",
    "Latitude": "40.81698295",
    "Longitude": "-73.92017897",
    "Phone": "(718) 993-5495",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "The Door",
    "Borough": "Manhattan",
    "Service": "Drop in",
    "Street_Address": "121 6th Avenue",
    "Latitude": "40.72412129",
    "Longitude": "-74.00516928",
    "Phone": "(212) 453-0248",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Project Hospitality",
    "Borough": "Staten Island",
    "Service": "Drop in",
    "Street_Address": "1546 Castleton Avenue",
    "Latitude": "40.63574444",
    "Longitude": "-74.13440428",
    "Phone": "(877) 994-6736",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "SCO Family of Services",
    "Borough": "Brooklyn",
    "Service": "Drop in",
    "Street_Address": "89 South 10th Street",
    "Latitude": "40.70832273",
    "Longitude": "-73.96509135",
    "Phone": "(718) 384-7083",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Bronx Community Pride Center",
    "Borough": "Bronx",
    "Service": "Drop in",
    "Street_Address": "448 East 149th Street",
    "Latitude": "40.81491019",
    "Longitude": "-73.91562948",
    "Phone": "(718) 292-4368",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  {
    "Center_Name": "Safe Horizon, Inc",
    "Borough": "Manhattan",
    "Service": "Drop in",
    "Street_Address": "209 West 125th Street",
    "Latitude": "40.80939075",
    "Longitude": "-73.94858861",
    "Phone": "(212) 695-2220",
    "URL": "http://www.nyc.gov/html/dycd/html/runaway/runaway.shtml",
    "Comments": "Runaway and Homeless Youth (RHY) services"
  },
  // {
  //   "Center_Name": "Good Shepherd Services",
  //   "Borough": "Manhattan",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "646.485.6900",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "Green Chimneys",
  //   "Borough": "Manhattan",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "212.491.5911 ext. 13",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "Girls Educational & Mentoring Services, Inc.",
  //   "Borough": "Manhattan",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "212.926.8089 ext. 25",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "Inwood House",
  //   "Borough": "Manhattan",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "212.861.4325",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "SCO Family of Services",
  //   "Borough": "Brooklyn",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.827.8465",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "SCO Family of Services",
  //   "Borough": "Brooklyn",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.782.0198",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "SCO Family of Services",
  //   "Borough": "Brooklyn",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.326.5931",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },
  // {
  //   "Center_Name": "SCO Family of Services IV",
  //   "Borough": "Queens",
  //   "Service": null,
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.217.5613",
  //   "URL": null,
  //   "Comments": null
  // },
  // {
  //   "Center_Name": "Safe Space NYC, Inc",
  //   "Borough": "Queens",
  //   "Service": null,
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.526.3000",
  //   "URL": null,
  //   "Comments": null
  // },
  // {
  //   "Center_Name": "Rachel's Place",
  //   "Borough": "Brooklyn",
  //   "Service": "Transitional Independent Living (TIL)",
  //   "Street_Address": null,
  //   "Latitude": null,
  //   "Longitude": null,
  //   "Phone": "718.253.5364",
  //   "URL": null,
  //   "Comments": "Transitional Independent Living (TIL)"
  // },

  {
    "Center_Name": "La Asociacion Benefica Cultural Father Billini",
    "Borough": "Queens",
    "Service": "Drop-In Center",
    "Street_Address": "104 11 37th Avenue",
    "Latitude": "40.749678220373596,",
    "Longitude": "-73.85304069",
    "Phone": "718.651.8427",
    "URL": null,
    "Comments": "Street Outreach"
  },
  {
    "Center_Name": "Safe Horizon, Inc",
    "Borough": "Manhattan",
    "Service": "Street Outreach",
    "Street_Address": "209 125th Street",
    "Latitude": "40.80915421",
    "Longitude": "-73.94868347",
    "Phone": "212.695.2220 or 800.708.6600",
    "URL": null,
    "Comments": "Drop-In Center"
  },
  {
    "Center_Name": "Greenwich Village Youth Council",
    "Borough": "Manhattan",
    "Service": "Drop-In Center",
    "Street_Address": "2273 3rd Avenue",
    "Latitude": "40.81329776",
    "Longitude": "-73.93728253",
    "Phone": "646.209.1264",
    "URL": null,
    "Comments": "Street Outreach"
  },
  {
    "Center_Name": "Ali Forney Center",
    "Borough": "Brooklyn",
    "Service": "Street Outreach",
    "Street_Address": "241 Taffee Place",
    "Latitude": "40.69159578",
    "Longitude": "-73.95963929",
    "Phone": "212.206.0574",
    "URL": null,
    "Comments": "Crisis Shelter"
  },
  {
    "Center_Name": "Safe Horizon",
    "Borough": "Manhattan",
    "Service": "Crisis Shelter",
    "Street_Address": "165 131st Street",
    "Latitude": "40.81234378",
    "Longitude": "-73.94449602",
    "Phone": "212.268.3943",
    "URL": null,
    "Comments": "Crisis Shelter"
  },
  {
    "Center_Name": "Covenant House New York / Under 21",
    "Borough": "Manhattan",
    "Service": "Crisis Shelter",
    "Street_Address": "427 52nd Street",
    "Latitude": "40.76527589",
    "Longitude": "-73.9892468",
    "Phone": "212.613.0300 ext. 0532",
    "URL": null,
    "Comments": "Crisis Shelter"
  },
  {
    "Center_Name": "Bronx Community Pride Center, Inc.",
    "Borough": "Bronx",
    "Service": "Drop-In Center",
    "Street_Address": "448 149th Street",
    "Latitude": "40.81541032",
    "Longitude": "-73.91617314",
    "Phone": "718.292.4368",
    "URL": null,
    "Comments": "Drop-In Center"
  },
  {
    "Center_Name": "Ali Forney Center",
    "Borough": "Brooklyn",
    "Service": "Crisis Shelter",
    "Street_Address": "216 23rd Street",
    "Latitude": "40.6606143",
    "Longitude": "-73.99529163",
    "Phone": "212.206.0574",
    "URL": null,
    "Comments": "Crisis Shelter"
  },
  {
    "Center_Name": "Seamans Society for Children and Families",
    "Borough": "Staten Island",
    "Service": "Drop-In Center",
    "Street_Address": "50 Bay Street",
    "Latitude": "40.63947645",
    "Longitude": "-74.0733153",
    "Phone": "718.447.7740 ext. 248",
    "URL": null,
    "Comments": "Drop-In Center"
  },
  {
    "Center_Name": "SCO Drop In Center",
    "Borough": "Brooklyn",
    "Service": "Crisis Shelter",
    "Street_Address": "89 10th Street",
    "Latitude": "40.67214091",
    "Longitude": "-73.99418393",
    "Phone": "718.384.7083",
    "URL": null,
    "Comments": "Drop-In Center"
  },
  {
    "Center_Name": "Covenant House New York / Under 21",
    "Borough": "Manhattan",
    "Service": "Transportation",
    "Street_Address": "460 41st Street",
    "Latitude": "40.75869417",
    "Longitude": "-73.99534286",
    "Phone": "212.613.0300 ext. 0531",
    "URL": null,
    "Comments": "Crisis Shelter"
  },
  {
    "Center_Name": "Safe Horizon, Inc",
    "Borough": "Manhattan",
    "Service": "Drop-In Center",
    "Street_Address": "209 125th Street",
    "Latitude": "40.80915421",
    "Longitude": "-73.94868347",
    "Phone": "212.695.2220",
    "URL": null,
    "Comments": "Transportation"
  },
  {
    "Center_Name": "Safe Space NYC, Inc",
    "Borough": "Queens",
    "Service": "Crisis Shelter",
    "Street_Address": null,
    "Latitude": "40.71311535",
    "Longitude": "-73.792821",
    "Phone": "718.526.2400",
    "URL": null,
    "Comments": "Drop-In Center"
  },
  {
    "Center_Name": "SUS",
    "Borough": "Manhattan",
    "Service": "Homebase",
    "Street_Address": "2276 Third Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "917-492-1019",
    "URL": null,
    "Comments": "East Harlem"
  },
  {
    "Center_Name": "SUS",
    "Borough": "Manhattan",
    "Service": "Homebase",
    "Street_Address": "265 Henry Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "917-492-1019",
    "URL": null,
    "Comments": "Lower East Side"
  },
  {
    "Center_Name": "Help USA I",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "775 Crotona Park North",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-299-8473",
    "URL": null,
    "Comments": "Crotona"
  },
  {
    "Center_Name": "Help USA I",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "3593 East 169th Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "917-801-4512",
    "URL": null,
    "Comments": "Claremont"
  },
  {
    "Center_Name": "Bronxworks",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "1130 Grand Concourse",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-508-3100",
    "URL": null,
    "Comments": "Grand Concourse"
  },
  {
    "Center_Name": "Bronxworks",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "630 Jackson Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-993-2032",
    "URL": null,
    "Comments": "Mott Haven"
  },
  {
    "Center_Name": "Help USA II",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "1780 Grand Concourse, Level I",
    "Latitude": null,
    "Longitude": null,
    "Phone": "347-226-4540",
    "URL": null,
    "Comments": "Mount Hope"
  },
  {
    "Center_Name": "Help USA II",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "1981 Sedgwick Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-215-6453",
    "URL": null,
    "Comments": "Morris Heights"
  },
  {
    "Center_Name": "ARCHNY I",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "2155 Blackrock Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-414-1050",
    "URL": null,
    "Comments": "Unionport"
  },
  {
    "Center_Name": "ARCHNY I",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "890 Garrison Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "929-259-9430",
    "URL": null,
    "Comments": "Hunts Point"
  },
  {
    "Center_Name": "ARCHNY II",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "2901 White Plains Road",
    "Latitude": null,
    "Longitude": null,
    "Phone": "347-913-4694",
    "URL": null,
    "Comments": "Bronxdale"
  },
  {
    "Center_Name": "ARCHNY II",
    "Borough": "Bronx",
    "Service": "Homebase",
    "Street_Address": "4377 Bronx Boulevard",
    "Latitude": null,
    "Longitude": null,
    "Phone": "347-947-3920",
    "URL": null,
    "Comments": "Woodlawn"
  },
  {
    "Center_Name": "CAMBA I",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "1117 Eastern Parkway",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-622-7323",
    "URL": null,
    "Comments": "Crown Heights"
  },
  {
    "Center_Name": "CAMBA I",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "1958 Fulton Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-408-5756",
    "URL": null,
    "Comments": "Bedford Stuyvesant"
  },
  {
    "Center_Name": "RBSCC",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "90 Beaver Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-366-4300",
    "URL": null,
    "Comments": "Bushwick"
  },
  {
    "Center_Name": "RBSCC",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "1475 Myrtle Avenue",
    "Latitude": null,
    "Longitude": null,
    "Phone": "347-295-3738",
    "URL": null,
    "Comments": "Bushwick North"
  },
  {
    "Center_Name": "RBSCC",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "145 East 98th Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "917-819-3200",
    "URL": null,
    "Comments": "Brownsville"
  },
  {
    "Center_Name": "CNS II",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "3060 Fulton Street",
    "Latitude": null,
    "Longitude": null,
    "Phone": "929-234-3036",
    "URL": null,
    "Comments": "East New York"
  },
  {
    "Center_Name": "CAMBA II",
    "Borough": "Staten Island",
    "Service": "Homebase",
    "Street_Address": "120 Stuyvesant Place, Suite 413",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-282-6473, EX. 75007",
    "URL": null,
    "Comments": "Staten Island"
  },
  {
    "Center_Name": "CNS I",
    "Borough": "Queens",
    "Service": "Homebase",
    "Street_Address": "87-80 Merrick Boulevard",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-674-1000",
    "URL": null,
    "Comments": "Jamaica"
  },
  {
    "Center_Name": "CNS I",
    "Borough": "Queens",
    "Service": "Homebase",
    "Street_Address": "Rockaways",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-647-1015",
    "URL": null,
    "Comments": "Rockaways"
  },
  {
    "Center_Name": "CAMBA II",
    "Borough": "Brooklyn",
    "Service": "Homebase",
    "Street_Address": "2211 Church Ave.",
    "Latitude": null,
    "Longitude": null,
    "Phone": "718-940-6311",
    "URL": null,
    "Comments": "Flatbush"
  }
]